-- migration_001_fix_strategy_scores_constraint.sql
-- Purpose : Add the missing UNIQUE(strategy) constraint to strategy_scores.
-- Run     : EXACTLY ONCE against the live Postgres database, BEFORE
--           restarting Docker with the patched main.py.
-- Safe    : Checks for duplicates first; aborts with a clear message if any
--           exist so you can inspect and merge them manually.
-- Author  : Generated by deployment pipeline 2026-07-08
--
-- The patched startup helper (_qfos_ensure_strategy_scores_constraint) checks
-- for this constraint by name and is a no-op if it already exists.
-- Constraint name expected by the code: strategy_scores_strategy_key

BEGIN;

-- Step 1: Abort if duplicate strategy rows exist.
-- If this raises an exception the transaction rolls back and nothing is changed.
DO $$
DECLARE
    dupe_count INTEGER;
BEGIN
    SELECT COUNT(*) INTO dupe_count
    FROM (
        SELECT strategy
        FROM strategy_scores
        GROUP BY strategy
        HAVING COUNT(*) > 1
    ) t;

    IF dupe_count > 0 THEN
        RAISE EXCEPTION
            'migration_001 ABORTED: strategy_scores has % strategy value(s) with duplicates. '
            'Inspect with: SELECT strategy, COUNT(*) FROM strategy_scores GROUP BY strategy HAVING COUNT(*) > 1; '
            'Merge or delete duplicates manually, then re-run this migration.',
            dupe_count;
    END IF;
END $$;

-- Step 2: Add the constraint (idempotent — skipped if it already exists).
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'strategy_scores_strategy_key'
    ) THEN
        ALTER TABLE strategy_scores
            ADD CONSTRAINT strategy_scores_strategy_key UNIQUE (strategy);
        RAISE NOTICE 'migration_001: UNIQUE(strategy) constraint added successfully.';
    ELSE
        RAISE NOTICE 'migration_001: constraint already exists — no change made.';
    END IF;
END $$;

COMMIT;

-- Post-migration verification (run these manually after COMMIT succeeds):
--
--   \d strategy_scores
--     → should show "strategy_scores_strategy_key UNIQUE, btree (strategy)"
--
--   SELECT COUNT(*) FROM (
--       SELECT strategy FROM strategy_scores
--       GROUP BY strategy HAVING COUNT(*) > 1
--   ) x;
--     → expected: 0
