CREATE TABLE IF NOT EXISTS trades (
    id SERIAL PRIMARY KEY,
    symbol TEXT NOT NULL,
    side TEXT NOT NULL,
    quantity DOUBLE PRECISION NOT NULL,
    expected_price DOUBLE PRECISION NOT NULL,
    fill_price DOUBLE PRECISION NOT NULL,
    slippage_bps DOUBLE PRECISION NOT NULL DEFAULT 0,
    pnl DOUBLE PRECISION NOT NULL DEFAULT 0,
    strategy TEXT NOT NULL,
    confidence DOUBLE PRECISION NOT NULL DEFAULT 0,
    live BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE TABLE IF NOT EXISTS portfolio_snapshots (
    id SERIAL PRIMARY KEY,
    equity DOUBLE PRECISION NOT NULL,
    cash DOUBLE PRECISION NOT NULL,
    exposure DOUBLE PRECISION NOT NULL,
    drawdown DOUBLE PRECISION NOT NULL,
    regime TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE TABLE IF NOT EXISTS strategy_scores (
    id SERIAL PRIMARY KEY,
    strategy TEXT NOT NULL,
    sharpe DOUBLE PRECISION NOT NULL,
    drawdown DOUBLE PRECISION NOT NULL,
    score DOUBLE PRECISION NOT NULL,
    status TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
